// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stepikEFPractice.Data;

#nullable disable

namespace stepikEFPractice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516092715_AddedCertificateModel")]
    partial class AddedCertificateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("stepikEFPractice.Models.Certificate", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasColumnName("grade");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issue_date");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("certificates");
                });

            modelBuilder.Entity("stepikEFPractice.Models.CertificateSetting", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("ExcellentThreshold")
                        .HasColumnType("int")
                        .HasColumnName("excellent_threshold");

                    b.Property<bool>("IsCertificateAutoIssued")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_certificate_auto_issued");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<int>("RegularThreshold")
                        .HasColumnType("int")
                        .HasColumnName("regular_threshold");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("signature_url");

                    b.HasKey("CourseId");

                    b.ToTable("certificate_settings");
                });

            modelBuilder.Entity("stepikEFPractice.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("stepikEFPractice.Models.SocialProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("social_providers");
                });

            modelBuilder.Entity("stepikEFPractice.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("units");
                });

            modelBuilder.Entity("stepikEFPractice.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<int>("DaysWithoutBreak")
                        .HasColumnType("int")
                        .HasColumnName("days_without_break");

                    b.Property<int>("DaysWithoutBreakMax")
                        .HasColumnType("int")
                        .HasColumnName("days_without_break_max");

                    b.Property<string>("Details")
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("int")
                        .HasColumnName("folowers_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("join_date");

                    b.Property<int>("Knowledge")
                        .HasColumnType("int")
                        .HasColumnName("knowledge");

                    b.Property<int>("Reputation")
                        .HasColumnType("int")
                        .HasColumnName("reputation");

                    b.Property<int>("SolvedTasks")
                        .HasColumnType("int")
                        .HasColumnName("solved_tasks");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("stepikEFPractice.Models.UserSocialProvider", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("SocialProviderId")
                        .HasColumnType("int")
                        .HasColumnName("social_provider_id");

                    b.Property<string>("ConnectUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("connect_url");

                    b.HasKey("UserId", "SocialProviderId");

                    b.HasIndex("SocialProviderId");

                    b.ToTable("user_social_providers");
                });

            modelBuilder.Entity("stepikEFPractice.Models.Certificate", b =>
                {
                    b.HasOne("stepikEFPractice.Models.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("stepikEFPractice.Models.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stepikEFPractice.Models.CertificateSetting", b =>
                {
                    b.HasOne("stepikEFPractice.Models.Course", null)
                        .WithOne("CertificateSetting")
                        .HasForeignKey("stepikEFPractice.Models.CertificateSetting", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("stepikEFPractice.Models.Unit", b =>
                {
                    b.HasOne("stepikEFPractice.Models.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("stepikEFPractice.Models.UserSocialProvider", b =>
                {
                    b.HasOne("stepikEFPractice.Models.SocialProvider", "SocialProvider")
                        .WithMany("UserSocialProviders")
                        .HasForeignKey("SocialProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("stepikEFPractice.Models.User", "User")
                        .WithMany("UserSocialProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stepikEFPractice.Models.Course", b =>
                {
                    b.Navigation("CertificateSetting")
                        .IsRequired();

                    b.Navigation("Certificates");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("stepikEFPractice.Models.SocialProvider", b =>
                {
                    b.Navigation("UserSocialProviders");
                });

            modelBuilder.Entity("stepikEFPractice.Models.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("UserSocialProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
