// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stepikEFPractice.Data;

#nullable disable

namespace stepikEFPractice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513054910_AddedNewObjects")]
    partial class AddedNewObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("stepikEFPractice.Models.CertificateSetting", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("ExcellentThreshold")
                        .HasColumnType("int")
                        .HasColumnName("excellent_threshold");

                    b.Property<bool>("IsCertificateAutoIssued")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_certificate_auto_issued");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<int>("RegularThreshold")
                        .HasColumnType("int")
                        .HasColumnName("regular_threshold");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("signature_url");

                    b.HasKey("CourseId");

                    b.ToTable("certificate_settings");
                });

            modelBuilder.Entity("stepikEFPractice.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("stepikEFPractice.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<int>("DaysWithoutBreak")
                        .HasColumnType("int")
                        .HasColumnName("days_without_break");

                    b.Property<int>("DaysWithoutBreakMax")
                        .HasColumnType("int")
                        .HasColumnName("days_without_break_max");

                    b.Property<string>("Details")
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("int")
                        .HasColumnName("folowers_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("join_date");

                    b.Property<int>("Knowledge")
                        .HasColumnType("int")
                        .HasColumnName("knowledge");

                    b.Property<int>("Reputation")
                        .HasColumnType("int")
                        .HasColumnName("reputation");

                    b.Property<int>("SolvedTasks")
                        .HasColumnType("int")
                        .HasColumnName("solved_tasks");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("stepikEFPractice.Models.CertificateSetting", b =>
                {
                    b.HasOne("stepikEFPractice.Models.Course", null)
                        .WithOne("CertificateSetting")
                        .HasForeignKey("stepikEFPractice.Models.CertificateSetting", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("stepikEFPractice.Models.Course", b =>
                {
                    b.Navigation("CertificateSetting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
